### ISSUE TITLE
Formatting output on stdput

### ISSUE THREAD

**Issue by BhaagBoseDK** [smallworlnd/stream-lnd-htlcs#4]
The current output on stdout not-reader friendly. 

Is it possible to format it as a table with header row and then one line per data. 

Event Type, EventOutcome, Incoming, OutGoing, OutCapacity, OutRemote, OutLocal, TimeStamp, EventOutcomeInfo

**Comment by smallworlnd** [comment]
For the default output I think I'd prefer to keep the JSON format since `event_outcome_info` can contain a few nested fields that aren't applicable across all `event_type`s. The nested fields would have to be flattened/expanded across several more (mostly sparse) columns. However, it can possibly be an option specified on the command line.
